---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/books":
    post:
      summary: Create a book
      tags:
      - Books
      parameters: []
      responses:
        '201':
          description: book created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                author:
                  type: string
              required:
              - title
              - author
servers:
- url: https://{defaultHost}/
  variables:
    defaultHost:
      default: localhost
